import { Project, WeeklyCapacity } from './types';
import { addWeeks, startOfWeek } from 'date-fns';

const today = new Date();
const weekStart = startOfWeek(today, { weekStartsOn: 1 });

export const projects: Project[] = [
  {
    id: 'proj-1',
    title: 'E-commerce Mobile App Redesign',
    description: 'Complete redesign of the mobile shopping experience to improve conversion rates and user satisfaction.',
    methodology: 'Double Diamond',
    timeline: '8 weeks',
    teamSize: 3,
    experienceLevel: 'Mid',
    weeklyAvailability: 30,
    status: 'active',
    progress: 45,
    startDate: addWeeks(weekStart, -2),
    endDate: addWeeks(weekStart, 6),
    estimatedHours: 240,
    phases: [
      {
        id: 'discover',
        name: 'Discover',
        description: 'Research and understand user needs',
        color: 'bg-blue-100 border-blue-300 text-blue-700',
        tasks: [
          {
            id: 'task-1',
            title: 'User Research & Interviews',
            description: 'Conduct 8-10 user interviews with current app users',
            phase: 'Discover',
            estimatedHours: 24,
            priority: 'High',
            status: 'done',
            startWeek: 0,
            duration: 1,
            projectId: 'proj-1',
            jiraDescription: 'Conduct comprehensive user interviews to understand shopping behaviors and pain points.',
          },
          {
            id: 'task-2',
            title: 'Analytics Review',
            description: 'Analyze app analytics and conversion funnel',
            phase: 'Discover',
            estimatedHours: 16,
            priority: 'High',
            status: 'done',
            startWeek: 0,
            duration: 1,
            projectId: 'proj-1',
            jiraDescription: 'Deep dive into analytics data to identify drop-off points and opportunities.',
          },
        ],
      },
      {
        id: 'define',
        name: 'Define',
        description: 'Synthesize insights and define problems',
        color: 'bg-purple-100 border-purple-300 text-purple-700',
        tasks: [
          {
            id: 'task-3',
            title: 'User Personas',
            description: 'Create 2-3 user personas based on research',
            phase: 'Define',
            estimatedHours: 16,
            priority: 'High',
            status: 'in-progress',
            startWeek: 2,
            duration: 1,
            projectId: 'proj-1',
            jiraDescription: 'Develop detailed user personas representing key segments.',
          },
          {
            id: 'task-4',
            title: 'Journey Mapping',
            description: 'Map current and future user journeys',
            phase: 'Define',
            estimatedHours: 20,
            priority: 'High',
            status: 'todo',
            startWeek: 2,
            duration: 1,
            projectId: 'proj-1',
            jiraDescription: 'Create comprehensive journey maps with pain points and opportunities.',
          },
        ],
      },
      {
        id: 'develop',
        name: 'Develop',
        description: 'Ideate and prototype solutions',
        color: 'bg-green-100 border-green-300 text-green-700',
        tasks: [
          {
            id: 'task-5',
            title: 'Wireframes',
            description: 'Create low-fidelity wireframes for key screens',
            phase: 'Develop',
            estimatedHours: 32,
            priority: 'High',
            status: 'todo',
            startWeek: 3,
            duration: 2,
            projectId: 'proj-1',
            jiraDescription: 'Design wireframes for all main user flows.',
          },
          {
            id: 'task-6',
            title: 'High-Fidelity Mockups',
            description: 'Design polished UI mockups',
            phase: 'Develop',
            estimatedHours: 40,
            priority: 'Medium',
            status: 'todo',
            startWeek: 5,
            duration: 2,
            projectId: 'proj-1',
            jiraDescription: 'Create pixel-perfect mockups with final visual design.',
          },
        ],
      },
      {
        id: 'deliver',
        name: 'Deliver',
        description: 'Test, refine, and handoff',
        color: 'bg-orange-100 border-orange-300 text-orange-700',
        tasks: [
          {
            id: 'task-7',
            title: 'Usability Testing',
            description: 'Test prototype with 6-8 users',
            phase: 'Deliver',
            estimatedHours: 24,
            priority: 'High',
            status: 'todo',
            startWeek: 7,
            duration: 1,
            projectId: 'proj-1',
            jiraDescription: 'Conduct usability testing sessions to validate design.',
          },
        ],
      },
    ],
  },
  {
    id: 'proj-2',
    title: 'Dashboard Analytics Redesign',
    description: 'Redesign the analytics dashboard to improve data visualization and user insights.',
    methodology: 'Lean UX',
    timeline: '4 weeks',
    teamSize: 2,
    experienceLevel: 'Senior',
    weeklyAvailability: 20,
    status: 'active',
    progress: 65,
    startDate: addWeeks(weekStart, -1),
    endDate: addWeeks(weekStart, 3),
    estimatedHours: 80,
    phases: [
      {
        id: 'think',
        name: 'Think',
        description: 'Define problems and hypotheses',
        color: 'bg-indigo-100 border-indigo-300 text-indigo-700',
        tasks: [
          {
            id: 'task-8',
            title: 'User Interviews',
            description: 'Interview key dashboard users',
            phase: 'Think',
            estimatedHours: 12,
            priority: 'High',
            status: 'done',
            startWeek: 0,
            duration: 1,
            projectId: 'proj-2',
            jiraDescription: 'Understand user needs and pain points with current dashboard.',
          },
          {
            id: 'task-9',
            title: 'Define Metrics',
            description: 'Identify key metrics to display',
            phase: 'Think',
            estimatedHours: 8,
            priority: 'High',
            status: 'done',
            startWeek: 0,
            duration: 1,
            projectId: 'proj-2',
            jiraDescription: 'Define which metrics matter most to users.',
          },
        ],
      },
      {
        id: 'make',
        name: 'Make',
        description: 'Create MVP solution',
        color: 'bg-pink-100 border-pink-300 text-pink-700',
        tasks: [
          {
            id: 'task-10',
            title: 'Dashboard Wireframes',
            description: 'Design dashboard layout and components',
            phase: 'Make',
            estimatedHours: 20,
            priority: 'High',
            status: 'in-progress',
            startWeek: 1,
            duration: 1,
            projectId: 'proj-2',
            jiraDescription: 'Create wireframes for new dashboard layout.',
          },
          {
            id: 'task-11',
            title: 'Interactive Prototype',
            description: 'Build clickable prototype',
            phase: 'Make',
            estimatedHours: 16,
            priority: 'Medium',
            status: 'todo',
            startWeek: 2,
            duration: 1,
            projectId: 'proj-2',
            jiraDescription: 'Build functional prototype for testing.',
          },
        ],
      },
      {
        id: 'check',
        name: 'Check',
        description: 'Test and validate',
        color: 'bg-cyan-100 border-cyan-300 text-cyan-700',
        tasks: [
          {
            id: 'task-12',
            title: 'Usability Testing',
            description: 'Test with 5 users',
            phase: 'Check',
            estimatedHours: 12,
            priority: 'High',
            status: 'todo',
            startWeek: 3,
            duration: 1,
            projectId: 'proj-2',
            jiraDescription: 'Validate dashboard design with users.',
          },
          {
            id: 'task-13',
            title: 'Iterate Based on Feedback',
            description: 'Refine design based on testing',
            phase: 'Check',
            estimatedHours: 12,
            priority: 'High',
            status: 'todo',
            startWeek: 3,
            duration: 1,
            projectId: 'proj-2',
            jiraDescription: 'Apply user feedback and finalize design.',
          },
        ],
      },
    ],
  },
  {
    id: 'proj-3',
    title: 'Design System Creation',
    description: 'Build a comprehensive design system for the product suite.',
    methodology: 'Agile UX',
    timeline: '12 weeks',
    teamSize: 4,
    experienceLevel: 'Senior',
    weeklyAvailability: 25,
    status: 'planning',
    progress: 15,
    startDate: addWeeks(weekStart, 1),
    endDate: addWeeks(weekStart, 13),
    estimatedHours: 300,
    phases: [
      {
        id: 'foundation',
        name: 'Foundation',
        description: 'Define design tokens and principles',
        color: 'bg-violet-100 border-violet-300 text-violet-700',
        tasks: [
          {
            id: 'task-14',
            title: 'Design Audit',
            description: 'Audit existing design patterns',
            phase: 'Foundation',
            estimatedHours: 20,
            priority: 'High',
            status: 'todo',
            startWeek: 1,
            duration: 1,
            projectId: 'proj-3',
            jiraDescription: 'Comprehensive audit of current design patterns across products.',
          },
          {
            id: 'task-15',
            title: 'Define Design Tokens',
            description: 'Create color, typography, spacing tokens',
            phase: 'Foundation',
            estimatedHours: 24,
            priority: 'High',
            status: 'todo',
            startWeek: 2,
            duration: 2,
            projectId: 'proj-3',
            jiraDescription: 'Define all design tokens for the system.',
          },
        ],
      },
    ],
  },
];

export const weeklyCapacity: WeeklyCapacity[] = [
  {
    weekStart: addWeeks(weekStart, 0),
    availableHours: 40,
    allocatedHours: 38,
    projects: [
      { projectId: 'proj-1', projectTitle: 'E-commerce Mobile App', hours: 22, color: 'bg-blue-500' },
      { projectId: 'proj-2', projectTitle: 'Dashboard Analytics', hours: 16, color: 'bg-purple-500' },
    ],
  },
  {
    weekStart: addWeeks(weekStart, 1),
    availableHours: 40,
    allocatedHours: 42,
    projects: [
      { projectId: 'proj-1', projectTitle: 'E-commerce Mobile App', hours: 24, color: 'bg-blue-500' },
      { projectId: 'proj-2', projectTitle: 'Dashboard Analytics', hours: 12, color: 'bg-purple-500' },
      { projectId: 'proj-3', projectTitle: 'Design System', hours: 6, color: 'bg-green-500' },
    ],
  },
  {
    weekStart: addWeeks(weekStart, 2),
    availableHours: 40,
    allocatedHours: 35,
    projects: [
      { projectId: 'proj-1', projectTitle: 'E-commerce Mobile App', hours: 20, color: 'bg-blue-500' },
      { projectId: 'proj-2', projectTitle: 'Dashboard Analytics', hours: 8, color: 'bg-purple-500' },
      { projectId: 'proj-3', projectTitle: 'Design System', hours: 7, color: 'bg-green-500' },
    ],
  },
  {
    weekStart: addWeeks(weekStart, 3),
    availableHours: 40,
    allocatedHours: 28,
    projects: [
      { projectId: 'proj-1', projectTitle: 'E-commerce Mobile App', hours: 16, color: 'bg-blue-500' },
      { projectId: 'proj-3', projectTitle: 'Design System', hours: 12, color: 'bg-green-500' },
    ],
  },
];
